name: star_in_me_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  simple_animations: ^1.3.3
  animated_splash: ^1.0.0
  loading: ^1.0.2
  modal_progress_hud: ^0.1.3
  shared_preferences: ^0.5.10
  email_validator: ^1.0.5
  google_sign_in: ^4.5.3
  linkedin_login: ^1.2.2
  dots_indicator: ^1.2.0
  carousel_pro: ^1.0.0
  font_awesome_flutter: 8.10.0
  

  dotted_border: ^1.0.6
  carousel_slider: ^2.3.1
  http: ^0.12.2
  flutter_svg: ^0.19.0
  dropdown_search: ^0.4.4


  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_storage: ^4.0.1

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/assets/Build-your-profile.jpg
    - images/assets/Events.jpg
    - images/assets/newImage.jpg
    - images/assets/Seek-guidance.jpg
    - ../Asset/Images/tsim_logo.png
    - ../Asset/Images/tsim_main_logo.png
    - ../Asset/Images/Welcome-Screen.jpg
    - ../Asset/Images/eventsslide/eventscreatives.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
